import { Octokit } from '@octokit/rest';
import { createOAuthAppAuth } from '@octokit/auth-oauth-app';

export interface GitHubUser {
  id: number;
  login: string;
  name: string | null;
  email: string | null;
  avatar_url: string;
  company: string | null;
  location: string | null;
}

export interface GitHubRepository {
  id: number;
  name: string;
  full_name: string;
  description: string | null;
  private: boolean;
  html_url: string;
  clone_url: string;
  ssh_url: string;
  created_at: string;
  updated_at: string;
  pushed_at: string | null;
  size: number;
  language: string | null;
}

export interface GitHubTokenData {
  access_token: string;
  token_type: string;
  scope: string;
}

export interface CreateRepositoryOptions {
  name: string;
  description?: string;
  private?: boolean;
  auto_init?: boolean;
  license_template?: string;
  add_readme?: boolean;
}

export class GitHubService {
  private client: Octokit | null = null;

  /**
   * Initialize GitHub client with access token
   */
  setAccessToken(token: string): void {
    this.client = new Octokit({
      auth: token
    });
  }

  /**
   * Exchange authorization code for access token
   */
  async exchangeCodeForToken(code: string): Promise<GitHubTokenData> {
    const auth = createOAuthAppAuth({
      clientType: 'oauth-app',
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!
    });

    const { token } = await auth({
      type: 'oauth-user',
      code,
      state: 'plusultra-oauth'
    });

    return {
      access_token: token,
      token_type: 'bearer',
      scope: 'repo,public_repo'
    };
  }

  /**
   * Get authenticated user information
   */
  async getUser(): Promise<GitHubUser> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    const { data } = await this.client.users.getAuthenticated();
    return data as GitHubUser;
  }

  /**
   * Get user's repositories
   */
  async getUserRepositories(): Promise<GitHubRepository[]> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    const { data } = await this.client.repos.listForAuthenticatedUser({
      sort: 'updated',
      per_page: 100
    });

    return data as GitHubRepository[];
  }

  /**
   * Create a new repository
   */
  async createRepository(options: CreateRepositoryOptions): Promise<GitHubRepository> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    const { data } = await this.client.repos.createForAuthenticatedUser({
      name: options.name,
      description: options.description || 'React Native app generated by PlusUltra',
      private: options.private || false,
      auto_init: options.auto_init || true,
      license_template: options.license_template || 'mit'
    });

    return data as GitHubRepository;
  }

  /**
   * Upload files to a repository (simplified approach)
   */
  async uploadProjectFiles(
    owner: string,
    repo: string,
    files: Map<string, string>,
    commitMessage: string = 'Initial commit: Generated React Native project'
  ): Promise<void> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    try {
      // Upload files one by one using the simpler createOrUpdateFile method
      for (const [path, content] of files) {
        const base64Content = Buffer.from(content).toString('base64');

        await this.client.repos.createOrUpdateFileContents({
          owner,
          repo,
          path,
          message: `${commitMessage} - ${path}`,
          content: base64Content,
        });
      }
    } catch (error) {
      console.error('Error uploading files to GitHub:', error);
      throw error;
    }
  }

  /**
   * Check if repository exists
   */
  async repositoryExists(owner: string, repo: string): Promise<boolean> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    try {
      await this.client.repos.get({ owner, repo });
      return true;
    } catch (error: any) {
      if (error.status === 404) {
        return false;
      }
      throw error;
    }
  }

  /**
   * Get repository contents
   */
  async getRepositoryContents(owner: string, repo: string, path: string = ''): Promise<any[]> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    const { data } = await this.client.repos.getContent({
      owner,
      repo,
      path
    });

    return Array.isArray(data) ? data : [data];
  }

  /**
   * Delete a repository
   */
  async deleteRepository(owner: string, repo: string): Promise<void> {
    if (!this.client) {
      throw new Error('GitHub client not initialized. Call setAccessToken() first.');
    }

    await this.client.repos.delete({ owner, repo });
  }

  /**
   * Get OAuth authorization URL
   */
  getOAuthUrl(state: string = 'plusultra-oauth'): string {
    const clientId = process.env.GITHUB_CLIENT_ID;
    if (!clientId) {
      throw new Error('GITHUB_CLIENT_ID environment variable is required');
    }

    const scope = 'repo,public_repo';
    const redirectUri = process.env.GITHUB_REDIRECT_URI || 'http://localhost:3000/auth/github/callback';

    return `https://github.com/login/oauth/authorize?client_id=${clientId}&scope=${scope}&state=${state}&redirect_uri=${redirectUri}`;
  }
}

// Export singleton instance
export const githubService = new GitHubService();
