import { GitHubService } from './GitHubService';
import archiver from 'archiver';
import fs from 'fs';
import path from 'path';
import { pipeline } from 'stream/promises';
import { createReadStream, createWriteStream } from 'fs';
import { extract } from 'tar';
import AdmZip from 'adm-zip';

export interface GitHubExportOptions {
  repositoryName: string;
  description?: string;
  private?: boolean;
  projectPath: string; // Path to the generated project files
  owner: string; // GitHub username
}

export interface GitHubExportResult {
  success: boolean;
  repositoryUrl?: string;
  cloneUrl?: string;
  error?: string;
}

/**
 * GitHubExportService
 * Orchestrates exporting generated projects to GitHub repositories
 */
export class GitHubExportService {
  constructor(private githubService: GitHubService) {}

  /**
   * Export a project to a GitHub repository
   * Creates the repository and uploads all project files
   */
  async exportProject(options: GitHubExportOptions): Promise<GitHubExportResult> {
    try {
      // Step 1: Check if repository already exists
      const repoExists = await this.githubService.repositoryExists(options.owner, options.repositoryName);

      if (repoExists) {
        return {
          success: false,
          error: `Repository ${options.owner}/${options.repositoryName} already exists`
        };
      }

      // Step 2: Create the repository
      const repository = await this.githubService.createRepository({
        name: options.repositoryName,
        description: options.description || 'React Native app generated by PlusUltra',
        private: options.private || false,
        auto_init: false // We'll upload our own initial commit
      });

      // Step 3: Read all project files from the project path
      const projectFiles = await this.readProjectFiles(options.projectPath);

      if (projectFiles.size === 0) {
        throw new Error('No project files found to upload');
      }

      // Step 4: Upload files to the repository in a single commit
      await this.uploadFilesToRepository(
        options.owner,
        options.repositoryName,
        projectFiles
      );

      return {
        success: true,
        repositoryUrl: repository.html_url,
        cloneUrl: repository.clone_url
      };
    } catch (error) {
      console.error('Error exporting project to GitHub:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred'
      };
    }
  }

  /**
   * Read all files from the project directory
   * Returns a Map of file paths to their contents
   */
  private async readProjectFiles(projectPath: string): Promise<Map<string, string>> {
    const files = new Map<string, string>();

    // Check if the path is a zip file or a directory
    const stats = await fs.promises.stat(projectPath);

    if (stats.isFile() && projectPath.endsWith('.zip')) {
      // Extract zip file and read contents
      return this.readZipFile(projectPath);
    } else if (stats.isDirectory()) {
      // Read directory recursively
      return this.readDirectory(projectPath);
    } else {
      throw new Error('Project path must be a directory or a zip file');
    }
  }

  /**
   * Read files from a zip archive
   */
  private async readZipFile(zipPath: string): Promise<Map<string, string>> {
    const files = new Map<string, string>();

    try {
      const zip = new AdmZip(zipPath);
      const zipEntries = zip.getEntries();

      for (const entry of zipEntries) {
        if (!entry.isDirectory) {
          const content = entry.getData().toString('utf-8');
          // Remove leading directory if present (e.g., "project-name/")
          const filePath = entry.entryName.replace(/^[^\/]+\//, '');
          if (filePath) {
            files.set(filePath, content);
          }
        }
      }
    } catch (error) {
      console.error('Error reading zip file:', error);
      throw error;
    }

    return files;
  }

  /**
   * Read files from a directory recursively
   */
  private async readDirectory(dirPath: string, basePath: string = ''): Promise<Map<string, string>> {
    const files = new Map<string, string>();
    const entries = await fs.promises.readdir(dirPath, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);
      const relativePath = basePath ? path.join(basePath, entry.name) : entry.name;

      // Skip common directories that shouldn't be committed
      if (entry.isDirectory()) {
        const skipDirs = ['node_modules', '.git', 'dist', 'build', '.expo', 'ios/Pods'];
        if (skipDirs.includes(entry.name)) {
          continue;
        }

        // Recursively read subdirectory
        const subFiles = await this.readDirectory(fullPath, relativePath);
        for (const [subPath, content] of subFiles) {
          files.set(subPath, content);
        }
      } else if (entry.isFile()) {
        // Skip binary files and large files
        const skipExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.ico', '.ttf', '.otf', '.woff', '.woff2', '.eot'];
        const ext = path.extname(entry.name).toLowerCase();

        if (skipExtensions.includes(ext)) {
          continue; // Skip binary files for now (can be enhanced later)
        }

        try {
          const content = await fs.promises.readFile(fullPath, 'utf-8');
          files.set(relativePath.replace(/\\/g, '/'), content); // Normalize path separators
        } catch (error) {
          console.warn(`Skipping file ${fullPath}:`, error);
          // Skip files that can't be read as UTF-8 (likely binary)
        }
      }
    }

    return files;
  }

  /**
   * Upload files to GitHub repository using Git Tree API
   * This creates a single commit with all files
   */
  private async uploadFilesToRepository(
    owner: string,
    repo: string,
    files: Map<string, string>
  ): Promise<void> {
    try {
      // For simplicity and reliability, we'll use the sequential upload approach
      // In production, you might want to use the Git Tree API for a single atomic commit
      await this.githubService.uploadProjectFiles(
        owner,
        repo,
        files,
        'Initial commit: PlusUltra generated project'
      );
    } catch (error) {
      console.error('Error uploading files to repository:', error);
      throw error;
    }
  }

  /**
   * Connect an existing repository to a project
   * This doesn't create a new repo, just validates it exists
   */
  async connectRepository(owner: string, repo: string): Promise<GitHubExportResult> {
    try {
      const exists = await this.githubService.repositoryExists(owner, repo);

      if (!exists) {
        return {
          success: false,
          error: `Repository ${owner}/${repo} does not exist`
        };
      }

      // Get repository details
      const repositories = await this.githubService.getUserRepositories();
      const repository = repositories.find(r => r.name === repo && r.full_name.startsWith(owner));

      if (!repository) {
        return {
          success: false,
          error: 'You do not have access to this repository'
        };
      }

      return {
        success: true,
        repositoryUrl: repository.html_url,
        cloneUrl: repository.clone_url
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred'
      };
    }
  }
}

export default GitHubExportService;
